### ISSUE TITLE
provider.readyPromise is not a function 

### ISSUE THREAD

**Issue by ilyaly** [hongfaqiu/TIFFImageryProvider#4]
When loading any .tiff file as proposed in a readme file:

```Javascript
provider.readyPromise().then(() => {
  cesiumViewer.imageryLayers.addImageryProvider(provider);
})
````

,I always get the error:

```Javascript
caught TypeError: provider.readyPromise is not a function
    at eval (index.js:33:10)
    at ./src/index.js (app.js:1702:1)
    at __webpack_require__ (app.js:13123:33)
    at app.js:14328:37
    at app.js:14330:12
```

I'am using Cesium 1.99 so this should not be a problem with deprecated API.

**Comment by hongfaqiu** [comment]
Sorry for my mistake. `readyPromise` is not a function but a promise, so you can use it as follows:
```ts
provider.readyPromise.then(() => {
  cesiumViewer.imageryLayers.addImageryProvider(provider);
})
```
or use the `await` keyword:
```ts
await provider.readyPromise
```
