### ISSUE TITLE
GeoTIFFImage.getTileOrStrip Fail when rendering large multiband tiff file

### ISSUE THREAD

**Issue by ilyaly** [hongfaqiu/TIFFImageryProvider#6]
When rendering 5 band 3.9 Gb .tiff file in `multi` mode the error described below often occurs. Looks like it does not lead to anything bad, but I decided to report it for further investigation if required.

```
index.js:2292 AggregateError: Request failed
    at BlockedSource.fetch (blockedsource.js:160:13)
    at async GeoTIFFImage.getTileOrStrip (geotiffimage.js:396:20)
    at async Promise.all (:8081/index 0)
    at async GeoTIFFImage._readRaster (geotiffimage.js:528:5)
    at async GeoTIFFImage.readRasters (geotiffimage.js:622:20)
```

[Data to reproduce the issue on Google Drive](https://drive.google.com/file/d/16-lfUiipD5j3CP8lD2SvIosGOAyz4YrB/view?usp=share_link).

**Comment by hongfaqiu** [comment]
This seems to be caused by a 304 cache error when fetching the data with a fetch request. The geotiff will spontaneously execute the request again, so it has no impact on the rendering.
